### ISSUE TITLE
PoolTogether requires your approval to transact Dai: Enable Dai

### ISSUE THREAD

**Issue by avalyn2** [pooltogether/pooltogether-contracts#22]
I am getting this message for the third time despite I already approved through my HW wallet (Ledger) and the transaction has been done already TWICE in the blockchain:

![image](https://user-images.githubusercontent.com/32930476/71771490-f3517800-2f3b-11ea-8bb3-42e346dbb375.png)

**Comment by avalyn2** [comment]
on the third attempt it finally worked. maybe in the popup window there should be written a message "PLEASE DO NOT CLOSE THIS WINDOW" to ensure the transaction in ethereum has finished.

**Comment by asselstine** [comment]
This is a front-end issue; where the app isn't updating it's state to reflect the chain state.  The app erroneously thinks that the token hasn't been approved yet.  

Thanks for the report, closing this issue as it's wrt the front-end app.
